GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
//Steam Engine
    event.create('particle_accelerator')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 2, 2) //Max Item Inputs, Max Item Outputs, Max Fluid Inputs, Max Fluid Outputs
        //.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC)
})
GTCEuStartupEvents.registry('gtceu:machine', event => {
//Steam Engine space_production
    event.create('particle_accelerator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('particle_accelerator')
        .appearanceBlock(() => Block.getBlock("gtceu:activated_netherite_frame"))
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' C            CCC            C ', 'COC         CCCXCCC         CIC', ' C            CCC            C ')
            .aisle(' C        CCCCCCCCCCC        C ', 'CPC      CCCPPPPPPPCCC      CPC', ' C        CCCCCCCCCCC        C ')
            .aisle(' C      CCCCCCCCCCCCCCC      C ', 'CPC    CCPPPCCCCCCCPPPCC    CPC', ' C      CCCCCCCCCCCCCCC      C ')
            .aisle(' C    CCCCC         CCCCC    C ', 'CPC   CPPPCC       CCPPPC   CPC', ' C    CCCCC         CCCCC    C ')
            .aisle(' C   CCCC             CCCC   C ', 'CPC  CPPCC           CCPPC  CPC', ' C   CCCC             CCCC   C ')
            .aisle(' C  CCC                 CCC  C ', 'CPC CPPC               CPPC CPC', ' C  CCC                 CCC  C ')
            .aisle(' C CCC                   CCC C ', 'CPCCPPC                 CPPCCPC', ' C CCC                   CCC C ')
            .aisle(' C CC                     CC C ', 'CPCPPC                   CPPCPC', ' C CC                     CC C ')
            .aisle(' CCCC                     CCCC ', 'CPCPC                     CPCPC', ' CCCC                     CCCC ')
            .aisle(' CCC                       CCC ', 'CPPPC                     CPPPC', ' CCC                       CCC ')
            .aisle(' CCC                       CCC ', ' CPC                       CPC ', ' CCC                       CCC ')
            .aisle(' CC                         CC ', ' CPC                       CPC ', ' CC                         CC ')
            .aisle(' CC                         CC ', 'CPC                         CPC', ' CC                         CC ')
            .aisle(' CC                         CC ', 'CPC                         CPC', ' CC                         CC ')
            .aisle('CCC                         CCC', 'CPC                         CPC', 'CCC                         CCC')
            .aisle('CCC                         CCC', 'KPC                         CPG', 'CCC                         CCC')
            .aisle('CCC                         CCC', 'CPC                         CPC', 'CCC                         CCC')
            .aisle(' CC                         CC ', 'CPC                         CPC', ' CC                         CC ')
            .aisle(' CC                         CC ', 'CPC                         CPC', ' CC                         CC ')
            .aisle(' CC                         CC ', ' CPC                       CPC ', ' CC                         CC ')
            .aisle(' CCC                       CCC ', ' CPC                       CPC ', ' CCC                       CCC ')
            .aisle(' CCC                       CCC ', 'CPPPC                     CPPPC', ' CCC                       CCC ')
            .aisle(' CCCC                     CCCC ', 'CPCPC                     CPCPC', ' CCCC                     CCCC ')
            .aisle(' C CC                     CC C ', 'CPCPPC                   CPPCPC', ' C CC                     CC C ')
            .aisle(' C CCC                   CCC C ', 'CPCCPPC                 CPPCCPC', ' C CCC                   CCC C ')
            .aisle(' C  CCC                 CCC  C ', 'CPC CPPC               CPPC CPC', ' C  CCC                 CCC  C ')
            .aisle(' C   CCCC             CCCC   C ', 'CPC  CPPCC           CCPPC  CPC', ' C   CCCC             CCCC   C ')
            .aisle(' C    CCCCC         CCCCC    C ', 'CPC   CPPPCC       CCPPPC   CPC', ' C    CCCCC         CCCCC    C ')
            .aisle(' C      CCCCCCCCCCCCCCC      C ', 'CPC    CCPPPCCCCCCCPPPCC    CPC', ' C      CCCCCCCCCCCCCCC      C ')
            .aisle(' C        CCCCCCCCCCC        C ', 'CPC      CCCPPPPPPPCCC      CPC', ' C        CCCCCCCCCCC        C ')
            .aisle(' C            CCC            C ', 'CIC         CCCACCC         COC', ' C            CCC            C ')
            .where('A', Predicates.controller(Predicates.blocks(definition.get())))
            .where('C', Predicates.blocks("gtceu:activated_netherite_frame")
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1).setMaxGlobalLimited(2))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .where('P', Predicates.blocks('gtceu:long_distance_fluid_pipeline'))
            .where('I', Predicates.abilities(PartAbility.IMPORT_FLUIDS_1X))
            .where('O', Predicates.abilities(PartAbility.EXPORT_FLUIDS_1X))
            .where('G', Predicates.abilities(PartAbility.IMPORT_ITEMS))
            .where('K', Predicates.abilities(PartAbility.EXPORT_ITEMS))
            .where('X', Predicates.blocks("gtceu:activated_netherite_frame")
                        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
            )
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingRenderer(
            'gfs:block/casings/machine_casing_netherite',
            'gtceu:block/multiblock/large_chemical_reactor', false
        )
})